version: '3.7'
services:
  mysql:
    image: mysql:8.0.30-oracle
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=masha
      - MYSQL_PASSWORD=mamamylaramu